/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Analyze
         * @description Analiza un titular contrastando todas las señales disponibles.
         *
         *     Devuelve **200 aunque alguna señal falle**: cada una lleva su propio
         *     `status`, y perder tres análisis correctos porque el cuarto dio timeout
         *     sería un error. Si el cuerpo de la noticia no se
         *     envía, la señal de incoherencia queda en `no_aplicable` y la dimensión de
         *     engaño no se puede evaluar.
         *
         *     Cada análisis queda registrado en el historial. Si esa escritura
         *     falla, la respuesta se devuelve igual: perder un análisis correcto porque el
         *     disco esté lleno sería peor que no guardarlo.
         */
        post: operations["post_analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tools
         * @description Catálogo de herramientas disponibles, descubierto en el momento.
         *
         *     No es un menú de lanzamiento: responde **qué compone el sistema y con qué
         *     límites**. Cada herramienta trae su categoría, de qué integración procede y
         *     —si es una señal de análisis— su ficha de modelo, con el tipo, la dimensión
         *     que mide y sus límites conocidos.
         *
         *     Devuelve **200 aunque un servidor MCP no responda**: sale en `servers` con
         *     estado `unreachable` y `degraded` queda a `true`, pero las herramientas de
         *     los demás se sirven igual.
         */
        get: operations["get_tools_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/{name}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Execute
         * @description Ejecuta una herramienta concreta con los argumentos indicados.
         *
         *     Para cuando no se quieren las cuatro señales —sólo el sentimiento, por
         *     ejemplo— o para traer una noticia con la que luego analizar.
         *
         *     Los argumentos se validan contra el `input_schema` que publica `/tools`
         *     **antes** de invocar, así que un campo mal escrito devuelve un 422 diciendo
         *     cuál, en vez de llegar como un fallo de ejecución indistinguible de un
         *     análisis que salió mal.
         *
         *     Devuelve **404** si la herramienta no existe, **422** si los argumentos no
         *     encajan, y **200 con `status` en `error`** si la herramienta se ejecutó y
         *     falló: eso último no es un error HTTP, porque la petición era correcta.
         *
         *     Y **504** si el servidor MCP tarda más de `mcp_execute_timeout`. Es una
         *     categoría aparte del `status: error` a propósito: al agotarse la espera la
         *     herramienta **puede haber terminado bien** —medido en #113, acabó con éxito a
         *     los 151 s mientras la API ya había desistido—, así que decir que el análisis
         *     falló sería falso. Lo que falló es la espera.
         */
        post: operations["post_execute_tools__name__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Análisis y ejecuciones anteriores, del más reciente al más antiguo.
         *
         *     Una entrada por **análisis**, no por herramienta invocada: un `/analyze`
         *     ejecuta cinco señales y produce una sola línea, con su titular y su
         *     veredicto. La traza de invocaciones vive en los logs, que es donde sirve.
         *
         *     Cada entrada trae la respuesta completa en `payload`, así que la interfaz
         *     puede volver a mostrar el resultado sin reejecutar — que además de tardar
         *     podría dar otro resultado, porque las señales remotas no son deterministas.
         *
         *     `limit` y `offset` se validan en la firma en vez de recortarse a mano dentro:
         *     así los topes salen publicados en el esquema OpenAPI —del que se genera el
         *     cliente Angular— y pedir de más devuelve un **422** diciendo cuál es el
         *     máximo, en vez de servir otra cosa en silencio.
         *
         *     El mínimo de 1 no es cosmético: en SQLite un **LIMIT negativo significa «sin
         *     límite»**, así que `?limit=-1` no daría error, traería la tabla ENTERA a
         *     memoria y la serializaría. Es el borde que hay que tapar, no el `?limit=9999`.
         *
         *     Los filtros se acumulan con AND y el `total` se calcula **ya filtrado**, para
         *     que la interfaz no pinte «1-3 de 500» sobre una lista de tres.
         *
         *     Hay dos parámetros donde el criterio hablaba de uno, y no es un descuido:
         *     `verdict` es **qué concluyó el análisis** y es el que le importa a quien mira
         *     sus análisis; `status` es **si funcionó la maquinaria** y es operativo. En la
         *     pantalla sólo el primero merece sitio destacado.
         *
         *     La respuesta incluye `retention` para que la interfaz pueda explicar por qué
         *     faltan los análisis viejos y acotar el selector de fechas sin cablear los
         *     números.
         */
        get: operations["get_history_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Estado de las integraciones externas.
         *
         *     Sondea cada API con una petición ligera y agrega: `ok` si todas responden,
         *     `degraded` si alguna falla, `down` si ninguna. Es el mismo sondeo que expone
         *     la tool MCP `health_check`.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Headline
             * @description Titular a analizar (en inglés).
             */
            headline: string;
            /**
             * Content
             * @description Cuerpo o teaser. Opcional: sin él, la señal de incoherencia queda en 'no_aplicable' y no se puede evaluar la dimensión de engaño.
             */
            content?: string | null;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Headline */
            headline: string;
            /** Content */
            content?: string | null;
            /** Signals */
            signals: components["schemas"]["SignalResult"][];
            /** Dimensions */
            dimensions: components["schemas"]["DimensionVerdict"][];
            verdict: components["schemas"]["OverallVerdict"];
        };
        /**
         * CatalogResponse
         * @description Catálogo completo: qué servidores se consultaron y qué ofrecen.
         */
        CatalogResponse: {
            /** Servers */
            servers: components["schemas"]["ServerInfo"][];
            /** Tools */
            tools: components["schemas"]["ToolInfo"][];
            /**
             * Degraded
             * @description ¿Falta algún servidor por responder?
             *
             *     Va como campo calculado y no como ``@property`` a secas porque la
             *     interfaz lo necesita EN EL JSON: una propiedad normal no se serializa,
             *     y obligaría al frontend a recorrer la lista para deducir lo mismo.
             */
            readonly degraded: boolean;
        };
        /**
         * Dimension
         * @description Qué mide una señal. Determina cómo se agrupan los veredictos.
         * @enum {string}
         */
        Dimension: "forma" | "engano" | "tono";
        /**
         * DimensionVerdict
         * @description Veredicto agregado de las señales que miden lo mismo (principio 3).
         *
         *     Solo aparecen las dimensiones en las que alguna señal llegó a emitir
         *     veredicto. Si ninguna lo hizo —fallaron, faltaba el cuerpo, o la dimensión
         *     no vota— la dimensión no se incluye, en vez de añadir un objeto vacío que la
         *     interfaz tendría que aprender a ignorar. El motivo no se pierde: está en la
         *     tarjeta de cada señal, que es donde el usuario lo lee.
         */
        DimensionVerdict: {
            dimension: components["schemas"]["Dimension"];
            /**
             * Is Clickbait
             * @description None si las señales de esta dimensión se contradicen: no se promedian ni se resuelven por mayoría, se declara la discrepancia.
             */
            is_clickbait?: boolean | null;
            /**
             * Contributing
             * @description Señales que han contribuido a este veredicto.
             */
            contributing?: string[];
        };
        /**
         * ExecuteRequest
         * @description Parámetros con los que invocar la herramienta.
         *
         *     Van en un diccionario libre y no en campos declarados porque **cada
         *     herramienta tiene los suyos**: la forma correcta la publica su
         *     ``input_schema`` en el catálogo, y contra ese esquema se validan antes de
         *     ejecutar.
         */
        ExecuteRequest: {
            /**
             * Arguments
             * @description Argumentos de la herramienta, según su `input_schema`.
             */
            arguments?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExecuteResponse
         * @description Resultado de ejecutar una herramienta.
         *
         *     Que la herramienta falle **no es un error HTTP**: la petición era válida y
         *     el servidor la atendió: lo que falló es el análisis. Por eso se responde 200
         *     con ``status`` en ``error``, igual que una señal caída en ``/analyze`` no
         *     tumba la respuesta. Los códigos de error se reservan para lo que sí es
         *     culpa de la petición: 404 si la herramienta no existe, 422 si los argumentos
         *     no encajan en su esquema.
         */
        ExecuteResponse: {
            /** Tool */
            tool: string;
            /** Server */
            server: string;
            status: components["schemas"]["ExecuteStatus"];
            /**
             * Data
             * @description Salida estructurada de la herramienta, tal como la declara su `output_schema`. Las que devuelven texto o listas llegan envueltas en `result`, porque el protocolo sólo deja sin envolver los objetos.
             */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Detail
             * @description Motivo legible cuando `status` es `error`.
             */
            detail?: string | null;
        };
        /**
         * ExecuteStatus
         * @description Cómo acabó la ejecución.
         * @enum {string}
         */
        ExecuteStatus: "ok" | "error";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryEntry
         * @description Una entrada del historial.
         *
         *     Sobre por qué unos campos son enums y otros cadenas sueltas: los enums
         *     describen lo que se calcula AHORA, y publican en OpenAPI el conjunto cerrado
         *     de valores para que el cliente pueda generar un tipo unión. Pero esto son
         *     **datos leídos de disco, que pudo escribir otra versión del código**, y un
         *     enum sobre eso es una bomba de relojería: el día que cambie un valor, las
         *     filas antiguas dejan de validar y `GET /history` devuelve un 500 por una
         *     entrada de hace seis meses.
         *
         *     De ahí el reparto: `kind` y `origin` son un conjunto minúsculo, estable y
         *     bajo nuestro control (si cambiara, se migraría a mano) → enum. `verdict`
         *     procede de ``OverallVerdict``, un vocabulario de dominio que va a CRECER
         *     conforme se añadan tipos de clickbait → cadena. `status` se queda en cadena
         *     porque su significado aún difiere entre tipos —en un análisis es «alguna
         *     señal funcionó», en una herramienta es «no falló»— y eso se replantea al
         *     llegar el filtrado (#103).
         */
        HistoryEntry: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            kind: components["schemas"]["HistoryKind"];
            origin: components["schemas"]["Origin"];
            /**
             * Headline
             * @description Titular analizado. Nulo en ejecuciones sueltas.
             */
            headline?: string | null;
            /**
             * Tool
             * @description Herramienta invocada. Nulo en análisis completos.
             */
            tool?: string | null;
            /**
             * Verdict
             * @description Veredicto global. Nulo en ejecuciones sueltas.
             */
            verdict?: string | null;
            /** Status */
            status: string;
            /**
             * Payload
             * @description La respuesta COMPLETA que se devolvió en su momento. Es lo que permite volver a mostrar el resultado sin reejecutar — que además de costar ~20 s podría dar otro resultado, porque las señales remotas no son deterministas.
             */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * HistoryKind
         * @description Define qué acción produjo la entrada en el historial.
         * @enum {string}
         */
        HistoryKind: "analysis" | "tool";
        /**
         * HistoryPage
         * @description Una página del historial, en orden cronológico inverso.
         */
        HistoryPage: {
            /** Items */
            items: components["schemas"]["HistoryEntry"][];
            /**
             * Total
             * @description Entradas totales que casan con el filtro, no las de esta página. La interfaz lo necesita para paginar; sin él sólo puede saber si hay más pidiendo la siguiente. Ojo con leerlo como «cuántos análisis he hecho»: con retención activa es «cuántos se conservan».
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            retention: components["schemas"]["RetentionPolicy"];
        };
        /**
         * Origin
         * @description Desde dónde se pidió la entrada en el historial. El prototipo distingue chat y formulario.
         * @enum {string}
         */
        Origin: "form" | "chat" | "api";
        /**
         * OverallVerdict
         * @description Etiqueta única, para listados compactos como el historial.
         *
         *     Se deriva de las dimensiones con una jerarquía explícita —el engaño pesa más
         *     que la forma— en lugar de por mayoría de señales.
         * @enum {string}
         */
        OverallVerdict: "enganoso" | "clickbait_de_forma" | "factual" | "ambiguo" | "sin_datos";
        /**
         * RetentionPolicy
         * @description Política de retención vigente, para que la interfaz no la cablee.
         *
         *     Va en la respuesta porque la pantalla la necesita para dos cosas, y las dos
         *     son de usabilidad, no de adorno:
         *
         *     1. **Explicar por qué faltan análisis viejos.** La poda es invisible, y eso
         *        es justo el problema: quien analizó algo hace cuarenta días y no lo
         *        encuentra no piensa «se habrá podado», piensa que la aplicación ha perdido
         *        sus datos. Un borrado silencioso se lee como un fallo.
         *     2. **Acotar el selector de fechas.** Un calendario libre que permita pedir
         *        «hace seis meses» y devuelva siempre vacío es una mala experiencia.
         *
         *     Y va aquí en vez de como constantes en Angular para que esos números salgan
         *     de la configuración REAL: cableados, se desincronizarían el día que cambie
         *     el `.env` y la pantalla seguiría prometiendo 30 días.
         */
        RetentionPolicy: {
            /**
             * Max Entries
             * @description Entradas conservadas. 0 = sin límite.
             */
            max_entries: number;
            /**
             * Max Days
             * @description Días conservados. 0 = sin límite.
             */
            max_days: number;
        };
        /**
         * ServerInfo
         * @description Un servidor MCP declarado en la configuración, respondiera o no.
         *
         *     Aparece aunque esté caído: es lo que convierte «seguir operando con los
         *     restantes y reflejar el estado degradado» en algo observable en vez de en
         *     una lista más corta sin explicación.
         */
        ServerInfo: {
            /** Url */
            url: string;
            /**
             * Name
             * @description Nombre que el propio servidor declara en el handshake.
             */
            name?: string | null;
            status: components["schemas"]["ServerStatus"];
            /**
             * Tool Count
             * @default 0
             */
            tool_count: number;
            /**
             * Detail
             * @description Motivo legible cuando no se pudo consultar.
             */
            detail?: string | null;
        };
        /**
         * ServerStatus
         * @description Estado de un servidor MCP consultado.
         * @enum {string}
         */
        ServerStatus: "ok" | "unreachable";
        /**
         * SignalResult
         * @description Resultado de UNA señal, con el mismo envoltorio sea cual sea (principio 1).
         */
        SignalResult: {
            /**
             * Name
             * @description Nombre de la herramienta MCP que la produjo.
             */
            name: string;
            status: components["schemas"]["SignalStatus"];
            dimension: components["schemas"]["Dimension"];
            /** @description Naturaleza del modelo, para el badge de la UI. */
            type: components["schemas"]["SignalType"];
            /**
             * Is Clickbait
             * @description Veredicto de esta señal, o None si no aporta ninguno: porque no pudo ejecutarse, o porque por naturaleza no lo emite (el tono). El agregado ignora los None en ambos casos; ``status`` distingue cuál de los dos ha sido.
             */
            is_clickbait?: boolean | null;
            /**
             * Data
             * @description JSON CRUDO devuelto por la herramienta, sin aplanar. Es lo que alimenta las tarjetas de explicabilidad (spans, top_cues, similitud...). No se transforma aquí para no perder información que la interfaz pueda necesitar.
             */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Detail
             * @description Motivo legible cuando no hay resultado: «requiere el cuerpo de la noticia», «el proveedor no respondió». Permite pintar la tarjeta en gris explicando por qué, en vez de omitirla sin más.
             */
            detail?: string | null;
        };
        /**
         * SignalStatus
         * @description Por qué una señal tiene o no resultado.
         * @enum {string}
         */
        SignalStatus: "ok" | "no_aplicable" | "error";
        /**
         * SignalType
         * @description Naturaleza del modelo. Se muestra como badge en la interfaz.
         *
         *     No mide cuán complejo es el modelo sino **dónde está la transparencia**:
         *     ``híbrido`` es decisión transparente sobre un rasgo opaco — un umbral legible
         *     aplicado a una similitud de embeddings, por ejemplo.
         * @enum {string}
         */
        SignalType: "interpretable" | "híbrido" | "opaco";
        /**
         * ToolInfo
         * @description Una herramienta del catálogo, con su procedencia y sus metadatos.
         */
        ToolInfo: {
            /** Name */
            name: string;
            /**
             * Description
             * @description Docstring de la tool, tal como la lee el LLM.
             */
            description?: string | null;
            /**
             * Input Schema
             * @description Esquema JSON de los parámetros, CRUDO. No se aplana: perdería las restricciones (mínimos, máximos, valores por defecto) que la interfaz necesita para validar el formulario antes de enviar.
             */
            input_schema: {
                [key: string]: unknown;
            };
            /**
             * Category
             * @description Qué tipo de trabajo hace: fuente, señal de análisis o utilidad.
             */
            category?: string | null;
            /**
             * Integration
             * @description Paquete del que procede (nyt, guardian, weather, nlp). None si es del núcleo y no envuelve ninguna fuente externa.
             */
            integration?: string | null;
            /**
             * Server
             * @description Servidor MCP que la expone.
             */
            server: string;
            /** @description Sólo para las señales de análisis; None para el resto. */
            model_card?: components["schemas"]["ToolModelCard"] | null;
        };
        /**
         * ToolModelCard
         * @description Ficha del modelo que hay detrás de una señal de análisis.
         *
         *     Es lo que evita que el catálogo enseñe «detect_clickbait_linear — Señales de
         *     análisis» y esconda que es interpretable, que mide forma y que su F1 cae
         *     fuera de dominio. Reutiliza los enums de las señales en vez de duplicar
         *     cadenas sueltas.
         */
        ToolModelCard: {
            type: components["schemas"]["SignalType"];
            dimension: components["schemas"]["Dimension"];
            /** Limitations */
            limitations: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tools_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    post_execute_tools__name__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecuteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description `analysis` o `tool`. Las pestañas de la pantalla. */
                kind?: components["schemas"]["HistoryKind"] | null;
                /** @description Nombre de la herramienta. Sólo casa con ejecuciones sueltas: un análisis invoca cinco señales y no tiene *una* herramienta. */
                tool?: string | null;
                /** @description Qué CONCLUYÓ el análisis: `enganoso`, `factual`, `ambiguo`… */
                verdict?: string | null;
                /** @description Si funcionó la MAQUINARIA: `ok` o `error`. Filtro operativo. */
                status?: string | null;
                /** @description Desde esta fecha, inclusive. Ojo: en una cadena de consulta `+` significa ESPACIO, así que un desfase escrito a pelo (`...T00:00:00+00:00`) llega roto y devuelve 422. Usa el sufijo `Z` o codifica el parámetro. */
                since?: string | null;
                /** @description Hasta esta fecha, inclusive. */
                until?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
